### ISSUE TITLE
apply_padding error

### ISSUE THREAD

**Issue by col-in-coding** [facebookincubator/AITemplate#104]
I got an error when compiling the ait model.

```
  File "compile.py", line 222, in compile_unet
    compile_model(Y, target, "./unet_epoch_0_step_100000", "UNet2DConditionModel", constants=params_ait)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/compiler.py", line 184, in compile_model
    graph = compiler.transform.optimize_graph(graph, test_dir)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/transform/optimize_graph.py", line 89, in optimize_graph
    sorted_graph = func(sorted_graph, workdir)
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/transform/apply_padding.py", line 218, in apply_padding
    new_op = type(op)()
TypeError: __init__() missing 1 required positional argument: 'shape'
```

print(op)

 { 'alpha': 1.0,
  'depth': 40,
  'epilogue': 'LinearCombination',
  'epilogue_alignment': 8,
  'f_ab_alignment': <function bmm_rrr.__init__.<locals>.cal_align_ab at 0x7fbf20d77d30>,
  'has_profiler': True,
  'input_accessors': [ { '_dim_mapping': [([0], [0]), ([1], [1]), ([2], [2])],
  'actual_shapes': None,
  'actual_total_elements_from_stride_dim': None,
  'is_contiguous': True,
  'is_from_strided_tensor': False,
  'offset': 0,
  'original_shapes': [ {'depth': 0, 'name': 'reshape_50_0_dim_0', 'nop': False, 'values': [16]},
                       {'depth': 0, 'name': 'reshape_50_0_dim_1', 'nop': False, 'values': [4096]},
                       {'depth': 0, 'name': 'reshape_54_0_dim_1', 'nop': False, 'values': [77]}],
  'original_total_elements_from_stride_dim': None,
  'stride_dim': None},
                       { '_dim_mapping': [([0], [0]), ([1], [1]), ([2], [2])],
  'actual_shapes': None,
  'actual_total_elements_from_stride_dim': None,
  'is_contiguous': True,
  'is_from_strided_tensor': False,
  'offset': 0,
  'original_shapes': [ {'depth': 0, 'name': 'reshape_60_0_dim_0', 'nop': False, 'values': [16]},
                       {'depth': 0, 'name': 'reshape_60_0_dim_1', 'nop': False, 'values': [77]},
                       {'depth': 0, 'name': 'reshape_60_0_dim_2', 'nop': False, 'values': [40]}],
  'original_total_elements_from_stride_dim': None,
  'stride_dim': None}],
  'inputs': [None, None],
  'layout': 'Permute4DBMM_0213',
  'name': 'bmm_rrr_permute_61',
  'nop': False,
  'num_sources': 0,
  'op': 'bmm_rrr_permute',
  'original_name': 'bmm_rrr_permute_61',
  'output_accessors': [ { '_dim_mapping': [([0], [0]), ([1], [1]), ([2], [2])],
  'actual_shapes': None,
  'actual_total_elements_from_stride_dim': None,
  'is_contiguous': True,
  'is_from_strided_tensor': False,
  'offset': 0,
  'original_shapes': [ {'depth': 0, 'name': 'reshape_50_0_dim_0', 'nop': False, 'values': [16]},
                       {'depth': 0, 'name': 'reshape_50_0_dim_1', 'nop': False, 'values': [4096]},
                       {'depth': 0, 'name': 'reshape_60_0_dim_2', 'nop': False, 'values': [40]}],
  'original_total_elements_from_stride_dim': None,
  'stride_dim': None}],
  'outputs': ['bmm_rrr_permute_61_0'],
  'permute_shape': '8',
  'shape': (8,),
  'split_k': 1,
  'workspace': 0}

**Comment by ipiszy** [comment]
Sorry for the late rely, for bmm_rrr_permute op, the last dimension of input tensors need to be divisible by 2. We'll update the error message to make it more accurate.

To address your issue, could you try [16, 4096, 78]?
