### ISSUE TITLE
Does AIT support conversion of BF16 trained models?

### ISSUE THREAD

**Issue by acostin1** [facebookincubator/AITemplate#110]
We would like to explore training in BF16 and we're wondering if we still have to convert the model to FP16 (with the potential to get overflows) of whether we could use BF16 natively during inference and whether this is supported and if it has the same performance profile.

**Comment by antinucleon** [comment]
Multiple data type will be supported in v0.2

**Comment by ipiszy** [comment]
We're working on BF16 support now. It will be ready around 2023Q1. cc @tenpercent

**Comment by acostin1** [comment]
Great to hear - looking forward!
