### ISSUE TITLE
Automatic AIT conversion from pytorch

### ISSUE THREAD

**Issue by darkbobin** [facebookincubator/AITemplate#117]
Hello, 

Thank you for your great work! I used AITemplate for conversion of [stable-diffusion-2-base](https://huggingface.co/stabilityai/stable-diffusion-2-base) that worked nicely.

However, I also tried to compile [stable-diffusion-x4-upscaler](https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler) built from [diffusers](https://github.com/huggingface/diffusers)>=0.9.0. Using the current [modeling](https://github.com/facebookincubator/AITemplate/tree/main/examples/05_stable_diffusion/modeling) created for old versions of the diffusers library, a dimension mismatch happened during the binding of tensors and constants.

I am wondering if you plan to release a way to convert a model directly from the PyTorch implementation without needing to rewrite all the diffusers pytorch modules as AIT modules?

Thank you

**Comment by ipiszy** [comment]
We plan to open source fx2ait in the next release (ETA 2023 Jan). It will enable the path Pytorch -> FX tracer -> FX2AIT -> AIT. However there are some limitations on the FX tracer side as it doesn't support control flow, so it's likely that the stable diffusion model won't work out of the box. For a better integration with Pytorch, stay tuned for PT2 -> Aten2AIT -> AIT.
