### ISSUE TITLE
Stable Diffusion pipeline: can't pass three text embeddings instead of two

### ISSUE THREAD

**Issue by nhnt11** [facebookincubator/AITemplate#124]
Usually the pipeline does:
`text_embeddings = torch.cat([uncond_embeddings, text_embeddings])`
which gets passed into `unet_inference()`.

If I add another one, let's say identicaly to `uncond_embeddings`:
`text_embeddings = torch.cat([uncond_embeddings, text_embeddings, uncond_embeddings])`
And expand latents appropriately, the eventual call to `run_with_tensors()` gives me this error:
`model_interface.cu:128: Error: [SetValue] Dimension got value out of bounds; expected value to be in [2, 2], but got 3`

This works fine outside of AITemplate.

I don't understand things deeply enough to fix this myself and thought I'd ask where the code is that expects a particular dimension and/or restricts it.

**Comment by nhnt11** [comment]
Is this just controlled by the batch size when compiling the unet? I think that might be it.

**Comment by ipiszy** [comment]
Yes, updating it to batch_size * 3 is correct.
