### ISSUE TITLE
[Bug] Cannot compile `gemm_rrr_bias`

### ISSUE THREAD

**Issue by lygztq** [facebookincubator/AITemplate#138]
I found `gemm_rrr_bias` op implementation in `python/aitemplate/compiler/ops/gemm_universal`, but I cannot find its backend implementation (e.g. `cuda.gemm_rrr_bias.config` function or other similar functions). Directly invoke this op will raise a runtime errror like `RuntimeError: cuda.gemm_rrr_bias.config function has not been registered.`.

Do you have plan for this operator?

**Comment by tissue3** [comment]
sorry we don't support this op at this moment as there is few kernel has such needs (e.g. linear is gemm_rcr_bias, not rrr). You can use gemm_rrr + elementwise(ADD) as a temporary solution.

**Comment by lygztq** [comment]
Thanks for the reply.
