### ISSUE TITLE
Changing parameters of a compiled model?

### ISSUE THREAD

**Issue by vpj** [facebookincubator/AITemplate#139]
Is there a way to change weights of a compiled model? Or recompile with new weights faster using the already calculated optimizations?

**Comment by terrychenism** [comment]
one thing you can do is to compile model without binding weight, then load the weights before inference.

**Comment by vpj** [comment]
Thanks!

**Comment by bonlime** [comment]
@vpj have you managed to "compile model without binding weight, then load the any weights you want before inference"?
