### ISSUE TITLE
[FEATURE] Support for NVidia's A10g

### ISSUE THREAD

**Issue by MatthieuTPHR** [facebookincubator/AITemplate#14]
Hello, thanks for this great project. 

Following this [request](https://github.com/facebookincubator/AITemplate/issues/12) it would be amazing to have support for NVidia's latest generation of inference GPUs: the A10g. 

They are roughly 2-3x faster than the T4 and very cheap w.r.t A100s. 

On another topic, if we wanted to add this support ourselves for this GPU type or any future GPU from NVidia what would be the process ?

**Comment by antinucleon** [comment]
I think it will be straightforward to add A10 support, only need to extend the profiling range a little bit. We will make A10 support this week.

**Comment by antinucleon** [comment]
I enabled A10 (by educated guess how it will output) in this PR: https://github.com/facebookincubator/AITemplate/pull/18

I think to provide better performance on A10, it requires a little bit more extension.

**Comment by Purvak-L** [comment]
+1 on @MatthieuTPHR's request. A10g are widely used for inference and are cheaper wrt to A100s. Can you elaborate a bit more on what extension?

**Comment by antinucleon** [comment]
I have enabled A10, because we don't have access to A10 I can't guess more on perf optimization for A10. Should be ok.

**Comment by harishprabhala** [comment]
> Hello, thanks for this great project.
> 
> Following this [request](https://github.com/facebookincubator/AITemplate/issues/12) it would be amazing to have support for NVidia's latest generation of inference GPUs: the A10g.
> 
> They are roughly 2-3x faster than the T4 and very cheap w.r.t A100s.
> 
> On another topic, if we wanted to add this support ourselves for this GPU type or any future GPU from NVidia what would be the process ?

Hey @MatthieuTPHR have you tried voltaml stable diffusion library? They support T4 and A10 acceleration and they claim to have the fastest inference speed for now.

**Comment by MatthieuTPHR** [comment]
Hello @harishprabhala looking at their metrics we get a faster inference using the Tensor RT. 

TensorRT recently added support for Flash Attention [here](https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion). 

With it we get 27 it/s on a A10G compared to the 17 it/s shown in VoltaML's github repo. 

On the A100, we get 36 it/s with pytorch and xformers too. I haven't benchmarked the TRT model on the A100 yet though

**Comment by harishprabhala** [comment]
> Hello @harishprabhala looking at their metrics we get a faster inference using Tensor RT. 
> 
> 
> 
> TensorRT recently added support for Flash Attention [here](https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion). 
> 
> 
> 
> With it we get 27 it/s on a A10G compared to the 17 it/s shown in VoltaML's github repo. 
> 
> 
> 
> On the A100, we get 36 it/s with pytorch and xformers too. I haven't benchmarked the TRT model on the A100 yet though

Hi. Do you have a working code of this? We're getting issues creating the engine file.

**Comment by harishprabhala** [comment]
> Hello @harishprabhala looking at their metrics we get a faster inference using Tensor RT.
> 
> TensorRT recently added support for Flash Attention [here](https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion).
> 
> With it we get 27 it/s on a A10G compared to the 17 it/s shown in VoltaML's github repo.
> 
> On the A100, we get 36 it/s with pytorch and xformers too. I haven't benchmarked the TRT model on the A100 yet though

Looks like they don't support GPUs with SM<80. So, technically for NVIDIA T4, V100 etc voltaML could be the fastest
