### ISSUE TITLE
stable diffusion PyTorch baseline without AMP 

### ISSUE THREAD

**Issue by xinli-git** [facebookincubator/AITemplate#142]
Thanks for the amazing work!

I have been trying to recreate the benchmark for stable diffusion, especially for the Unet portion. 

However, I realized a subtle difference between how PyTorch model was executed vs AIT model is executed.

- For PyTorch, model is using FP16 weights are run under `autocast`, this probably means that GEMM and CONV are running under FP16 whereas normalization + some element-wise operators are running under FP32. (see [documentation](https://pytorch.org/docs/stable/amp.html#op-eligibility))
- For AIT, it seems that UNET is directly compiled without autocast [in this line](https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/compile.py#L208), also that the accumulatino for GEMM is set to be FP16

I am wondering if that is the case, and if so, would this change affect inference time experience? Or perhaps there is somewhere in the codebase that I missed the autocast for AIT?
It does appear that **without autocast**, PyTorch model performs much faster (latency for 100 inference dropped down from 7s to 5s on my local GPU)

Best,

**Comment by terrychenism** [comment]
Thanks for your finding. Yes, for PT the speed can be speed up if disable "autocast", on my side 5.3 it/s -> 7.2 it/s
but it won't effect any perf on AIT, since we used all fp16 ops and accumulation for all SD pipeline.
