### ISSUE TITLE
How to select GPU device?

### ISSUE THREAD

**Issue by bes-dev** [facebookincubator/AITemplate#150]
For multi-gpu systems, AITemplate Model launches on GPU with device_id=0. Is it possible to select other device without using env variables like CUDA_VISIBLE_DEVICES?

**Comment by yinghai** [comment]
Programmably, you can call cudaSetDevice before loading and running AIT model (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g159587909ffa0791bbe4b40187a4c6bb)
