### ISSUE TITLE
Compile failed for fx2ait module

### ISSUE THREAD

**Issue by Frozenmad** [facebookincubator/AITemplate#180]
Hi, I am trying to compile the fx2ait module follow the compile from source method but encounter the following error:

```log
[ 33%] Building CXX object CMakeFiles/ait_model.dir/fx2ait/csrc/AITModel.cpp.o
In file included from /xxx/AITemplate/fx2ait/fx2ait/csrc/AITModel.cpp:1:
/xxx/AITemplate/fx2ait/fx2ait/csrc/AITModel.h: In member function ‘void torch::aitemplate::AITModel::profile(std::vector<at::Tensor>, const string&, int64_t)’:
/xxx/AITemplate/fx2ait/fx2ait/csrc/AITModel.h:40:5: error: ‘TORCH_CHECK_GE’ was not declared in this scope; did you mean ‘TORCH_CHECK_MSG’?
   40 |     TORCH_CHECK_GE(num_iters, 0);
      |     ^~~~~~~~~~~~~~
      |     TORCH_CHECK_MSG
make[2]: *** [CMakeFiles/ait_model.dir/build.make:63: CMakeFiles/ait_model.dir/fx2ait/csrc/AITModel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ait_model.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

My device is RTX 3090 and my cuda version is 11.6. My pytorch version is 1.12.1.
What could be the problem?

**Comment by tissue3** [comment]
You might need to get the installation of PyTorch linked to more up-to-date CUDA:
$ with-proxy conda install pytest numpy jinja2 -y
$ with-proxy pip install torch==1.13.1+cu117 -f https://download.pytorch.org/whl/torch_stable.html
$ with-proxy conda install -c conda-forge parameterized -y

**Comment by Frozenmad** [comment]
It works! Thanks for the reply.
