### ISSUE TITLE
Missing `/AITemplate/tests/nightly/unittest.sh`

### ISSUE THREAD

**Issue by YukeWang96** [facebookincubator/AITemplate#181]
does the unitest missing in the current version?
```
/AITemplate/tests/nightly/unittest.sh
```

**Comment by ipiszy** [comment]
Are you using docker? I think it's missing in the docker file, but you can always run unittests directly in the source repo.
Follow https://github.com/facebookincubator/AITemplate#from-source to install AITemplate, and then run tests under https://github.com/facebookincubator/AITemplate/tree/main/tests/unittest directly.

**Comment by YukeWang96** [comment]
Yes, I am using docker but I mount with the existing release of AITemplate repo, like 
```
docker run --gpus all -v $PWD/../:/ait -w /ait -it ati:latest /bin/bash
```
I guess this file performs unitest as well.
```
https://github.com/facebookincubator/AITemplate/blob/main/tests/unittest/test_stable_set.py
```

**Comment by chenyang78** [comment]
BTW, running all the unittests may take a long time (e.g. several hours) to finish if you cannot do it in parallel.
