### ISSUE TITLE
Include and linking additional libraries in adding custom_ops

### ISSUE THREAD

**Issue by YukeWang96** [facebookincubator/AITemplate#186]
Is there any tutorial to specify `-I` or `-L` additional header or libraries when adding the custom_op in AItemplate?

**Comment by yinghai** [comment]
https://github.com/facebookincubator/AITemplate/blob/c2ebb9f5ec05dd8b732ab6a84e74dda85cfb84e8/fx2ait/CMakeLists.txt#L4 should include necessary -I and -L, Turn in verbose mode for cmake/make with VERBOSE=1 should show the actual gcc command.

**Comment by YukeWang96** [comment]
Thanks for your reply. I will try that out.
Meanwhile, I notice the CUDA backend for CUTLASS has the position to specify the option for compilation.
1. https://github.com/facebookincubator/AITemplate/blob/f7878c907167b41423d63e5355fc2685cda58f8e/python/aitemplate/backend/cuda/target_def.py#L102-L123
2. https://github.com/facebookincubator/AITemplate/blob/f7878c907167b41423d63e5355fc2685cda58f8e/python/aitemplate/backend/cuda/target_def.py#L257-L283

Should I add my customized external library path to this option as well?  Thanks a lot!

**Comment by chenyang78** [comment]
> Thanks for your reply. I will try that out. Meanwhile, I notice the CUDA backend for CUTLASS has the position to specify the option for compilation.

Currently, we don't provide any way to customize compilation options. Probably we should've. In the meanwhile, you could add your own options in the first location below. 

> 
> 1. https://github.com/facebookincubator/AITemplate/blob/f7878c907167b41423d63e5355fc2685cda58f8e/python/aitemplate/backend/cuda/target_def.py#L102-L123

Yes, this is the place to add your own compilation options. If you want to add any extra linker option, you may modify the code at:

```
https://github.com/facebookincubator/AITemplate/blob/f7878c907167b41423d63e5355fc2685cda58f8e/python/aitemplate/backend/builder.py#L285
```

> 2. https://github.com/facebookincubator/AITemplate/blob/f7878c907167b41423d63e5355fc2685cda58f8e/python/aitemplate/backend/cuda/target_def.py#L257-L283
> 
> Should I add my customized external library path to this option as well? Thanks a lot!

You only need to modify ```1``` for your experiments. The options pointed by ```2``` are internal use only. Thanks.

**Comment by YukeWang96** [comment]
Thanks a lot. It works and the path being added is shown up during the compilation when running the example `06_add_custom_op`. 
I notice another problem is when I rebuild the template by using 
```
cd python
python3 setup.py bdist_wheel
pip3 install dist/*.whl --force-reinstall
cd ..
```
files or directory under `/usr/local/lib/python3.8/dist-packages/aitemplate/3rdparty` seems unchanged even a new directory has been created. is there any step missing or I should just hard copy the new directory to that path?

**Comment by YukeWang96** [comment]
Thanks a lot for the suggestion. 
Just figure out one solution, I add the entry to `python/setup.py`
```
def gen_dgsparse_lib_list():
    srcs = ["aitemplate/3rdparty/mylib"]
    f_cond = lambda x: True
    return gen_file_list(srcs, f_cond)
```
And then do the above rebuild process and now it works fine without error.

**Comment by chenyang78** [comment]
@YukeWang96 Hi Yuke, regarding how to include your custom CUDA kernels, you may put your kernels into some ```jinja2``` templates (e.g. https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/backend/common/split_common.py#L39) or place them into CUDA files and then load the CUDA files from the codegen (e.g. https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/backend/cuda/layernorm_sigmoid_mul/layernorm_sigmoid_mul.py#L127-L129)
