### ISSUE TITLE
[Feature Request] Add pixel_shuffle

### ISSUE THREAD

**Issue by styler00dollar** [facebookincubator/AITemplate#201]
[PixelShuffle](https://pytorch.org/docs/stable/generated/torch.nn.PixelShuffle.html) is often used in super resolution tasks like [SRVGGNetCompact](https://github.com/xinntao/Real-ESRGAN/blob/master/realesrgan/archs/srvgg_arch.py) for example. I would appreciate support.

![grafik](https://user-images.githubusercontent.com/51405565/216767430-77a8d30f-5a04-4990-900c-488cea94ba96.png)

**Comment by tissue3** [comment]
We probably won't add these features per request, but you are more than welcomed to add them.
If you are interested, here is howto:
Implementation:

Add to acc_tracer: https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/acc_tracer/acc_ops.py
Add to converter the implementation: https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/converters/ait_converters.py
Add corresponding tests:
https://github.com/facebookincubator/AITemplate/tree/main/fx2ait/fx2ait/test/converters

Feel free to create pull reqeust and we will review them.
