### ISSUE TITLE
[Feature Request] Add floor_div

### ISSUE THREAD

**Issue by styler00dollar** [facebookincubator/AITemplate#202]
I think adding a floor div should be easy to do. I encountered this while trying to use [real-cugan](https://github.com/nullArrayList/Real-CUGAN/blob/master/upcunet_v3.py).
![grafik](https://user-images.githubusercontent.com/51405565/216767819-67c81626-65e7-46d3-b503-e12c2c21e01d.png)

**Comment by tissue3** [comment]
We probably won't add these features per request. 
But you are more than welcomed to add them. If you are interested, here is howto:
Implementation:
1. Add to acc_tracer: https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/acc_tracer/acc_ops.py
2. Add to converter the implementation: https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/converters/ait_converters.py
Add corresponding tests:
https://github.com/facebookincubator/AITemplate/tree/main/fx2ait/fx2ait/test/converters
