### ISSUE TITLE
[Bug] Stable Diffusion Upscaler compilation is failing

### ISSUE THREAD

**Issue by darkbobin** [facebookincubator/AITemplate#206]
I tried to compile the unet module of the checkpoint of the Stable Diffusion Upscaler [stable-diffusion-x4-upscaler](https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler) but I am facing the following error message over AIT compilation (while CLIP and VAE compilation works well):

`ConstantTensor's maximum size is not equal to len(data)! Got len(data)=1048576, but expected at least 524288 bytes. Check that the ConstantTensor's size and dtype are correct.`

I attached the code I used for the compilation.
[sd_upscaler_ait.zip](https://github.com/facebookincubator/AITemplate/files/10664625/sd_upscaler_ait.zip)

Thanks

**Comment by terrychenism** [comment]
Currently AIT v0.2 does not support upsampling model.
