### ISSUE TITLE
I want to use a custom pipeline for Diffusers, but it doesn't work

### ISSUE THREAD

**Issue by jyouj** [facebookincubator/AITemplate#303]
Hi.

I was able to use AITemplate to speed up Stable Diffusion v2.1. It was very impressive speed.

However, using a custom pipeline when Stable Diffusion was running on diffusers, I could no longer benefit from AITemplate.
Specifically, I am trying to use a custom pipeline for the number of tokens and weighting of prompts.

When I loaded a custom pipeline, as in the following code, the speed was not much different than when using diffusers.

```
scheduler = EulerAncestralDiscreteScheduler.from_config(model_id, subfolder="scheduler")
vae = AutoencoderKL.from_pretrained(model_id, subfolder="vae")
pipe = StableDiffusionAITPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float32,
    revision="fp32",
    custom_pipeline="lpw_stable_diffusion",
    scheduler=scheduler,
)
pipe = pipe.to("cuda")
```

Is there any way to successfully benefit from AITemplate even when using a custom pipeline?

**Environment**
- python3.8.10
- cuda11.6
- ubuntu
- NVIDIA A100

Thank you.

**Comment by terrychenism** [comment]
You need to customized StableDiffusionAITPipeline for your "lpw_stable_diffusion" in https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/src/pipeline_stable_diffusion_ait.py, like load the AIT model, and set input/output, then you'll get speed-up.

**Comment by jyouj** [comment]
Thank you!!!!

**Comment by djj0s3** [comment]
@jyouj can you show me how you got it working? there's another community pipeline I'm trying to speed up but I'm a bit lost on how to make it all work.
