### ISSUE TITLE
[Question] Compile GPT-NeoX 8bit model?

### ISSUE THREAD

**Issue by apivovarov** [facebookincubator/AITemplate#325]
Hugging Face API allows to load pre-trained Causal LM models in 8bit (parameter `load_in_8bit=True`). e.g.
```
model_name = "EleutherAI/gpt-neox-20b"
model = AutoModelForCausalLM.from_pretrained(model_name, load_in_8bit=True, device_map="auto")
```
Internally it uses:
- [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) - 8-bit optimizers, matrix multiplication (LLM.int8()), and quantization functions
- [accelerate](https://github.com/huggingface/accelerate)  - library that enables the same PyTorch code to be run across any distributed configuration

Is it possible to compile that 8bit models using AIT?

**Comment by tenpercent** [comment]
Hi @apivovarov, we don't have int8 support yet in AITemplate - though plan to add it eventually. We will probably start with fp8 first, and it should be ready in Q2
