### ISSUE TITLE
time -f issue

### ISSUE THREAD

**Issue by apivovarov** [facebookincubator/AITemplate#329]
Recently it was a [change](https://github.com/facebookincubator/AITemplate/commit/ff5615cb0683b590101eadc6b0f9d48710a22016) which adds  `time -f` command to `backend/builder.py`

In Ubuntu 20.04 `time` is a shell keyword. It is not a `GNU time`. And it does not support `-f` option.
Can we avoid using `-f` option?
```
$ time -f
-f: command not found

$ type time
time is a shell keyword
```
Ubuntu 20.04 is a base for [NVIDIA Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) containers - nvcr.io/nvidia/pytorch:23.01-py3

Related Ubuntu [discussion](https://askubuntu.com/questions/434289/why-doesnt-the-time-command-work-with-any-option)

**Comment by Stax124** [comment]
Same issues here, compilation fails due to the time command - using the official AIT Docker image:

```
/bin/sh: 1: exec: time: not found
make: *** [Makefile:6: gemm_rcr_bias_permute/gemm_rcr_bias_permute_24def307149b586a9cbe912b13f70195efa083ca_2] Error 127
make: *** Waiting for unfinished jobs....
/bin/sh: 1: exec: time: not found
make: *** [Makefile:9: gemm_rcr_bias_add/gemm_rcr_bias_add_9e46850d5286ecc7e078b5b7f76afbcac62967b4_2] Error 127
/bin/sh: 1: exec: time: not found
make: *** [Makefile:12: gemm_rcr_bias/gemm_rcr_bias_9e46850d5286ecc7e078b5b7f76afbcac62967b4_2] Error 127
```

**Comment by ipiszy** [comment]
Sorry just saw this discussion. I don't have a Ubuntu env, wonder does "/usr/bin/time" exist on Ubuntu without manually installing it? "apt" does not exist on Linux distributions like CentOS so it's not generic to add "apt install" to build docker. If by default Ubuntu /user/bin/time does not exist, I'll add an env to guard this timing logic.

**Comment by apivovarov** [comment]
AITemplate Dockerfiles for `cuda` and `rocm` use `ubuntu20.04` as a base image.

The Dockerfiles already use `apt` to install `python3`, `tzdata` and many other packages.

- [Dockerfile.cuda#L21](https://github.com/facebookincubator/AITemplate/blob/main/docker/Dockerfile.cuda#L21)
- [Dockerfile.rocm#L34](https://github.com/facebookincubator/AITemplate/blob/main/docker/Dockerfile.rocm#L34)
- [install_detection_deps.sh](https://github.com/facebookincubator/AITemplate/blob/main/docker/install/install_detection_deps.sh#L3)

**Comment by ipiszy** [comment]
I see, makes sense, thank you!

**Comment by ipiszy** [comment]
Will merge your PR. #347 is not necessary.

**Comment by apivovarov** [comment]
Particular developers might be interested in enabling `AIT_TIME_COMPILATION=1`.

Problem is that now ALL users need to install `time` package (unless they use AIT Docker image). But most of the users are not interested in getting compilation time info.
Let merge your [PR 347](https://github.com/facebookincubator/AITemplate/pull/347) to improve users experience and remove strict requirement to install `time` pkg.
