### ISSUE TITLE
how to debug `"Error in function: AITemplateModelContainerRun` for dimension other than 512x512 in the SD pipeline

### ISSUE THREAD

**Issue by archywillhe** [facebookincubator/AITemplate#35]
So we go into this: `Error in function: AITemplateModelContainerRun`, which looks to be something to do with the DLL:

```
self.DLL.AITemplateModelContainerRun(
                self.handle,
                c_inputs,
                ctypes.c_size_t(len(inputs)),
                c_outputs,
                ctypes.c_size_t(len(outputs)),
                c_stream,
                ctypes.c_bool(sync),
                ctypes.c_bool(graph_mode),
                c_output_shapes_out,
            )
```

We tried all different demensions that are multiple of 64 and it is still giving the same rror.

What is the best way to debug this? Or could this caused by a bug at a lower level?

**Comment by antinucleon** [comment]
The example model is compiled for 512x512, so the output binary doesn’t support other shapes. To fully support all shapes with **best** performance, it required at least one to two releases.

**Comment by archywillhe** [comment]
ooh aww thanks for the lightning response! Just saw the release notes; so that means we need this:

> Better dynamic shape support: Focus on the dynamic sequence in Transformers.

Thanks! Looking forwards!
