### ISSUE TITLE
 model_interface.cu:200: Error: [SetValue] Dimension got value out of bounds; expected value to be in [2, 2], but got 1.

### ISSUE THREAD

**Issue by ifk-tiger** [facebookincubator/AITemplate#353]
When I try to get 512*512, 2 result I encountered with this error. Any solution?

diffusers: 0.10.2
transformers: 4.25.1
torch: 1.12.1+cu113

`Traceback (most recent call last):   File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context    return func(*args, **kwargs)  File "/usr/src/app/ai_template/src/pipeline_stable_diffusion_ait.py", line 265, in __call__    text_embeddings = self.clip_inference(text_input.input_ids.to(self.device))  File "/usr/src/app/ai_template/src/pipeline_stable_diffusion_ait.py", line 153, in clip_inference    exe_module.run_with_tensors(inputs, ys, graph_mode=False)  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 535, in run_with_tensors    outputs_ait = self.run(  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 438, in run    return self._run_impl(  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 377, in _run_impl    self.DLL.AITemplateModelContainerRun(  File "/usr/local/lib/python3.8/dist-packages/aitemplate/compiler/model.py", line 181, in _wrapped_func    raise RuntimeError(f"Error in function: {method.__name__}")RuntimeError: Error in function: AITemplateModelContainerRun`

**Comment by muchulee8** [comment]
Hi, could you share the full cmd/changes that you've used?

**Comment by ifk-tiger** [comment]
Okey I forgot give prompt list instead of string to pipeline. Thanks.
