### ISSUE TITLE
[Question] Sparse Tensor Core Ops

### ISSUE THREAD

**Issue by collinmccarthy** [facebookincubator/AITemplate#361]
Hello,

Does AITemplate support sparse * dense matmul with 2-of-4 sparsity, using sparse tensor cores? In CUTLASS this would be `cutlass::device::SparseGemm` I believe. I'm looking to write some custom kernels based on the CUTLASS implementation and was wondering if I could use AITemplate rather than CUTLASS directly, both to make my life easier and to take advantage of fusion. 

Thank you,
-Collin

**Comment by muchulee8** [comment]
Hi Collin,

Unfortunately we do not support sparse cases right now.

**Comment by collinmccarthy** [comment]
Okay, thank you for the response. Any plans to support `cutlass::device::SparseGemm` specifically in the near future?
