### ISSUE TITLE
Build/install doesn't work

### ISSUE THREAD

**Issue by aifartist** [facebookincubator/AITemplate#365]
git clone --recursive https://github.com/facebookincubator/AITemplate
cd AITemplate
cd python
python3 setup.py bdist_wheel
error: invalid command 'bdist_wheel'
python3 setup.py bdist_wheel
 Try a second time and now
FileExistsError: [Errno 17] File exists: './aitemplate/3rdparty'

Am I not follow the instructions exactly from README.md?
Although I'm using python3, bdist_wheel is not a target in setup.py.

**Comment by muchulee8** [comment]
Do you have wheel installed? (`pip3 install wheel`)

**Comment by aifartist** [comment]
pip3 list | egrep whe
wheel                    0.38.4

and egads I tried again after bringing up a new window right now to check for wheel, setting my venv, and trying again.  It worked!?  I have no clue how I screwed up.
Sorry.

**Comment by aifartist** [comment]
User error?
