### ISSUE TITLE
Benchmark and multithread

### ISSUE THREAD

**Issue by pommedeterresautee** [facebookincubator/AITemplate#44]
I have a question over the computation of the latency in the cpp benchmark function.

Below `accumulate` applies a `max` over each thread output:

https://github.com/facebookincubator/AITemplate/blob/44026ba7e7f5376a80cf0f2b333a0f25c0eeda6c/static/csrc/model_container.cpp#L224

```cpp
  auto max_time = std::accumulate(
      futures.begin(), futures.end(), 0.f, [](float cur_val, auto& future) {
        return std::max(future.get(), cur_val);
      });
```

So, my understanding is that max_time is the longest time of all threads and not the total time taken.

Later on, `max_time` value is divided by the total nb of inferences performed by all threads.

https://github.com/facebookincubator/AITemplate/blob/44026ba7e7f5376a80cf0f2b333a0f25c0eeda6c/static/csrc/model_container.cpp#L256

```cpp
  auto total_num_iters = num_threads * count;
  return max_time / total_num_iters;
```

I don't understand why accumulate performs a `max` instead of a `sum` (of total time for each thread) if we divide it by `num_threads * count`.

**Comment by mikeiovine** [comment]
The threads are executing concurrently, so the total time taken to complete all inferences is the maximum over all threads, not the sum. At the same time, the number of inferences performed in that time scales with the number of threads.

**Comment by pommedeterresautee** [comment]
Thank you it's now clear to me.
Closing
