### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by mathpopo** [facebookincubator/AITemplate#47]
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/AITemplate/docker$ ./build.sh cuda
Building CUDA Docker Image with tag ait:latest
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/chenxin/disk1/github/AITemplate/docker/docker: no such file or directory

**Comment by mathpopo** [comment]
@antinucleon thank you for your help
i have created docker, but i use "sudo docker run -it -v /usr/bin/:/apps ait:latest"
root@2ebbd1eec037:/apps# ./nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
root@2ebbd1eec037:/apps# ldd ./nvidia-smi
	linux-vdso.so.1 (0x00007ffefe5d1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5c6e5ea000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5c6e5e4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5c6e3f2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5c6e3e8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5c6e618000)

**Comment by mathpopo** [comment]
root@01246f0349b6:/# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

**Comment by mathpopo** [comment]
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/AITemplate$ nvidia-smi
Thu Oct 20 21:12:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8     3W /  N/A |     11MiB /  6078MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1145      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2085      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

**Comment by antinucleon** [comment]
I don't know details about NVIDIA docker driver requirement, please check NVIDIA document for reference.
