### ISSUE TITLE
Index Tensor with Tensor

### ISSUE THREAD

**Issue by OrangeSodahub** [facebookincubator/AITemplate#49]
I want to ask how to index tensor with tensor just like torch.tensor:
```python
# pytorch
x=x[x.argmax(dim=-1)]
```
I only find the `ops.argmax()` in AIT, but how could I index another `Tensor` with the argmax results whose type would also be `Tensor`?

**Comment by antinucleon** [comment]
Tensor as index args is currently not supported. What model is using this feature? If it is widely used case we will consider to add support for it.

**Comment by OrangeSodahub** [comment]
@antinucleon Hi, thanks for your answering. I'm trying to implement ait model for openai CLIPVisionTransformer now: https://github.com/openai/CLIP/blob/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1/clip/model.py#L354

**Comment by antinucleon** [comment]
We need to extend dynamic slice op to accept input of a size 1 Tensor (currently only accept IntVar). 

A quick hack will be like adding a op to “cast” tensor to IntVar, where in backend it is doing a sync memcpy from gpu memory to cpu int memory. Then all current dynamic slice op can be used.

We will add this feature in the next release. Thank you so much for pointing out this missing feature.

**Comment by OrangeSodahub** [comment]
Is this op supported now?
