### ISSUE TITLE
batch inference benchmark for stable diffusion example

### ISSUE THREAD

**Issue by carlushuang** [facebookincubator/AITemplate#514]
Hi, for `examples/05_stable_diffusion`
https://github.com/facebookincubator/AITemplate/blob/f82ceb9d84c10bc6f20db7a2120af642bc8e1516/examples/05_stable_diffusion/src/benchmark.py#L276-L280
I see there is an assert to make sure `batch size == 1`. for PR: https://github.com/facebookincubator/AITemplate/pull/8 added support for batch inference, but seems we still can not benchmark it due to this assert?

**Comment by chenyang78** [comment]
Thanks for raising the issue. It seems to be an oversight to me. Adding @terrychenism to confirm. Thanks.

**Comment by terrychenism** [comment]
We disable multi-batch for benchmark due to OOM issue when enable pytorch inference.

**Comment by chenyang78** [comment]
> We disable multi-batch for benchmark due to OOM issue when enable pytorch inference.

I see. Thanks for the information!

@carlushuang Based on Terry's response, I am closing the issue. Thanks.
