### ISSUE TITLE
AIT's performance compared with PT's

### ISSUE THREAD

**Issue by OrangeSodahub** [facebookincubator/AITemplate#55]
I have a question, have you tested the ait-model's performance compared with pt-model? Given the same input (fp32 to pt-model while fp16 to ait-model), how would the two outputs be? Differences exist I think, and these differences are generated by what? Could you give us some detailed official descriptions?

**Comment by terrychenism** [comment]
We already provided fp16 data inputs for pytorch and aitemplate as benchmark for all of examples.  If you feed fp32 to pt, the results may not perfectly match with ait outputs.

**Comment by OrangeSodahub** [comment]
@terrychenism  Thanks. And Did you test on your side? How the difference would be if the inputs are correct?

**Comment by antinucleon** [comment]
It depends on numerical range. For most network with normalization layer and initialized in common range 1e-1 to 1e-2 is fine. If the network numerical is very bad, eg, weights range is in [-10, 10], then it requires adjust accordingly.
