### ISSUE TITLE
Conv2dBiasFewChannels issue with map_pt_params

### ISSUE THREAD

**Issue by dashesy** [facebookincubator/AITemplate#58]
When using `Conv2dBiasFewChannels` with a C=3 input, `special_conv2d_bias_activation` calls `nhwc3to4` to pad the tensor, so the convolution weights shape is recorded with 4 channels instead of 3.

When using `map_pt_params` in `compile_model` results in this error:

```text
ValueError: ConstantTensor's maximum size is not equal to len(data)! Got len(data)=75264, but expected at least 100352 bytes. Check that the ConstantTensor's size and dtype are correct.
```

The error message could be a little more helpful to print out the name and size of the parameter tensor that does not match.
It took me some time, and the workaround is to pad the weights. 
This should be documented

**Comment by terrychenism** [comment]
you need to pad the weight to 4 channel and set the weights, e.g. https://github.com/facebookincubator/AITemplate/blob/main/examples/01_resnet-50/weight_utils.py#L147

**Comment by dashesy** [comment]
Closing this. Still would be nice to add this to documentations.

Using this works:

```python
def map_pt_params(ait_model, pt_model):
  ait_model.name_parameter_tensor()
  pt_params = dict(pt_model.named_parameters())
  mapped_pt_params = OrderedDict()
  # names should be valid C++ variables
  for name, _ in ait_model.named_parameters():
    ait_name = name.replace(".", "_")
    assert name in pt_params
    params = pt_params[name]
    if len(params.shape) == 4:
        # NCHW->NHWC
        params = params.transpose(1,-1).contiguous()
        # Pad for few channels
        if params.shape[-1] == 3:
             params = torch.nn.functional.pad(params, (0,1))
    mapped_pt_params[ait_name] = params
  return mapped_pt_params
```
