### ISSUE TITLE
When will quant and sparsity features be finished? 

### ISSUE THREAD

**Issue by wenqibiao** [facebookincubator/AITemplate#605]
When will these two features be finished? 
1) Quantization: fp8/int8/int4.
2) Sparsity pruning for Gemm.

I am very much looking forward to :)

**Comment by terrychenism** [comment]
We are still working on it, will be ready in the future release.
If you don't want to wait, you can check out cutlass int8 examples https://github.com/NVIDIA/cutlass/blob/7c04f954151f606e60608061e891785fba229ae2/test/unit/gemm/device/gemm_s8t_s8n_f16t_tensor_op_s32_sm80.cu and add it to AITemplate follow by GEMM op https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/backend/cuda/gemm_universal/common.py

**Comment by wenqibiao** [comment]
Thank you!

> We are still working on it, will be ready in the future release. If you don't want to wait, you can check out cutlass int8 examples https://github.com/NVIDIA/cutlass/blob/7c04f954151f606e60608061e891785fba229ae2/test/unit/gemm/device/gemm_s8t_s8n_f16t_tensor_op_s32_sm80.cu and add it to AITemplate follow by GEMM op https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/backend/cuda/gemm_universal/common.py
