### ISSUE TITLE
Stable Diffusion example is failing 

### ISSUE THREAD

**Issue by causten** [facebookincubator/AITemplate#650]
Not sure why but "Ldm update #611" reverted some but not all of the SD scripts from 2.1 -> 1.5.  

The scripts/download_pipeline.py pushes for 1.5, but line 34 of scripts/compile.py uses v2 (not even 2.1).  I also see the requested path in demo.py (line 32)

It works when I explicitly set the path
```python3 scripts/compile.py --local-dir ./tmp/diffusers-pipeline/runwayml/stable-diffusion-v1-5/``` 

Actual error...

root@72d3aeb1f652:/AITemplate/examples/05_stable_diffusion# python3 scripts/compile.py
INFO:aitemplate.backend.build_cache_base:Build cache disabled
2023-05-03 01:39:27,327 INFO <aitemplate.testing.detect_target> Set target to CUDA
Traceback (most recent call last):
  File "scripts/compile.py", line 100, in <module>
    compile_diffusers()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/compile.py", line 51, in compile_diffusers
    pipe = StableDiffusionPipeline.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/pipeline_utils.py", line 884, in from_pretrained
    cached_folder = cls.download(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1208, in download
    config_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './tmp/diffusers-pipeline/stabilityai/stable-diffusion-v2'. Use `repo_type` argument if needed.

**Comment by terrychenism** [comment]
seems the error is not from AIT itself, can you upgrade your diffusers
`pip3 install diffusers --upgrade` and run again

**Comment by causten** [comment]
```
pip3 install diffusers --upgrade
Requirement already up-to-date: diffusers in /usr/local/lib/python3.8/dist-packages (0.16.1)
```

I built the docker today seems to be up to date.  You can clearly see the incorrect paths in the files listed above

**Comment by terrychenism** [comment]
Oh i didn't notice you mentioned "works with --local sd 1.5". will have a quick fix.

**Comment by causten** [comment]
Any idea why AIT benchmark move back to 1.5?

**Comment by terrychenism** [comment]
1. SDv1.5 seems to be the most common one, many download tasks are based on V1.5 instead of v2.0+
2. AIT also support v2.0+ ckpt, feel free to play with it and let me know if you have any issue.

**Comment by causten** [comment]
> 1. SDv1.5 seems to be the most common one, many downstream tasks are based on V1.5 instead of v2.0+
> 2. AIT also support v2.0+ ckpt, feel free to play with it and let me know if you have any issue.

I tried reverting to the commit just before 611 but it seems benchmark.py does not have a batch-size option at that point.    2.0 does give a better performance result.

**Comment by terrychenism** [comment]
Yeah sd 2.0 has some architecture change, so the perf gain is from model arch itself. 
You can enable batch-size option for benchmark if you have a100-80g GPU, smaller mem gpu would have OOM due to PT inference.

**Comment by artbred** [comment]
@causten did you manage to measure performance for 2.1? Can you please share your results and the images dimension

**Comment by terrychenism** [comment]
should be fixed by https://github.com/facebookincubator/AITemplate/pull/654
