### ISSUE TITLE
[Feature Request] Example for MIDAS 

### ISSUE THREAD

**Issue by olegchomp** [facebookincubator/AITemplate#678]
Hi! 
It would be great to have example (like with SD, detectotrone and resnet) for MiDaS Depth estimation model.

**Comment by terrychenism** [comment]
Thank you for your suggestion. I think MiDaS Depth estimation model would indeed be valuable for ControlNet right? Regarding your question, is it the model you mentioned at this link: https://github.com/isl-org/MiDaS/blob/master/midas/midas_net.py. I believe that following the ResNet example should not be overly challenging. If you need any further assistance, please feel free to ask.

**Comment by hl475** [comment]
Close this issue as we don't heard any updates in the past few weeks. Feel free to re-open if you need further assistance. Thanks!
