### ISSUE TITLE
compilation fails on example 05

### ISSUE THREAD

**Issue by MDCurrent** [facebookincubator/AITemplate#738]
feel free to close if this is not constructive but I haven't been able to succesfully run this code for a couple of weeks 
```
# create image
./docker/build.sh cuda
# run image 
docker run --gpus all -it ait:latest
# download pipeline 
python3 scripts/download_pipeline.py --token ...

# compile SD 
python3 scripts/compile.py
 RuntimeError: Failed to create cutlass library lib: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/3rdparty/cutlass/tools/library/scripts'

# check that dir 
ls /usr/local/lib/python3.8/
dist-packages
```
I assume im overlooking something dead simple but wanted to see if you all might know what is causing this. I've been keeping up to date with main as I've struggled through this

**Comment by tenpercent** [comment]
Hi @MDCurrent - just in case, have you cloned the submodules under `3rdparty` folder before creating a Docker image?

**Comment by MDCurrent** [comment]
I see the 3rdparty modules on my host machine in the AITemplate repo yea
```
/AITemplate$ ls 3rdparty/
composable_kernel  cub  cutlass  picojson
```
but I haven't manually cloned them to the usr/local/lib/python3.8/  directory

Thank you for your time and attention

**Comment by MDCurrent** [comment]
```
nvidia-smi --query-gpu=compute_cap --format=csv
compute_cap
7.5
```
Looks like my card is not the [proper generation.](https://github.com/facebookincubator/AITemplate/issues/37#issuecomment-1274078877) Will close this to represent the hardware incompatibility
