### ISSUE TITLE
[fx2ait] "Input shapes of the elementwise op are not compatible" while running bert model

### ISSUE THREAD

**Issue by ymwangg** [facebookincubator/AITemplate#753]
I'm trying to run huggingface bert model using torch.compile and fx2ait:
```py
import transformers
import torch
import logging
import copy
from fx2ait.lower.lower import AitLowerer
from fx2ait.lower.lower_settings import LowerSettings
torch._logging.set_logs(dynamo=logging.INFO,inductor=logging.INFO)

def ait_backend(gm, example_inputs):
    # return gm.forward
    lower = AitLowerer.create(
        LowerSettings(workdir="/tmp", name="test_ait_lower", min_acc_module_size=0)
    )
    lowered = lower(gm, example_inputs)
    return lowered

device = torch.device("cuda:0")
model = transformers.BertForMaskedLM.from_pretrained("bert-base-uncased")

model.eval()
model.cuda()
ref_model = copy.deepcopy(model)

ins = {'input_ids': torch.randint(0, 10, size=(12, 512)).to(device), 'attention_mask': torch.ones(12, 512, dtype=torch.int64).to(device)}

# ait_backend = "inductor"
model = torch.compile(model, backend=ait_backend)
res = model(**ins)
ref_res = ref_model(**ins)

torch.testing.assert_close(res, ref_res, rtol=1e-3, atol=1e-3)
```

However, I'm getting the following error:
```
BackendCompilerFailed: backend='ait_backend' raised:
ValueError: Input shapes of the elementwise op are not compatible! Shape1: [{'depth': 0, 'name': None, 'nop': False, 'symbolic_value': 12, 
'values': [12]}, {'depth': 0, 'name': None, 'nop': False, 'symbolic_value': 12, 'values': [12]}, {'depth': 0, 'name': None, 'nop': False, 
'symbolic_value': 512, 'values': [512]}, {'depth': 0, 'name': None, 'nop': False, 'symbolic_value': 512, 'values': [512]}], shape2: 
[{'depth': 0, 'name': None, 'nop': False, 'symbolic_value': 12, 'values': [12]}, {'depth': 0, 'name': None, 'nop': False, 'symbolic_value': 
1, 'values': [1]}, {'depth': 0, 'name': None, 'nop': False, 'symbolic_value': 1, 'values': [1]}, { 'depth': 0,
  'name': 'batch_size',
  'nop': False,
  'symbolic_value': batch_size,
  'values': [1, 2048]}]

While executing %add_40 : [#users=1] = call_function[target=fx2ait.acc_tracer.acc_ops.add](args = (), kwargs = {input: %truediv_12, other: 
%mul_1})
```

It looks like there are issues with broadcasting. I checked this torch.add operator takes `torch.Size([12, 12, 512, 512])` and `torch.Size([12, 1, 1, 512])` shaped tensor as inputs. I saw the last dim value of the second tensor appears to be [1,2048], does this mean the bounds of this dim?

**Comment by hl475** [comment]
Hi @ymwangg , currently AITemplate/fx2ait does not work/support with `torch.comiple`

**Comment by ymwangg** [comment]
Ok, it appears torch.compile is not quite relevant here. The issue is this model has a graph with input shape `[torch.Size([12, 1, 1, 512]), torch.Size([12, 512, 768]), torch.Size([12, 512, 768]), torch.Size([1, 512, 768])]` while the shape specs returned by ` input_specs = TensorSpec.from_input_list_with_batch_size(inputs,self.lower_settings.max_batch_size)`  is: `[torch.Size([12, 1, 1, [1, 2048]]), torch.Size([12, [1, 2048], 768]), torch.Size([12, [1, 2048], 768]), torch.Size([1, [1, 2048], 768])]`.
It appears this [function](https://github.com/facebookincubator/AITemplate/blob/6bc3253ab29e056140640ca2d847749d73c2a243/fx2ait/fx2ait/tensor_spec.py#L402-L450) wrongly inferred dim 1 because 512 is a number that exists in all input tensors. This batch dim inference mechanism looks hacky and does not guarantee correctness. Is there a way for the user to manually annotate input batch dim?
