### ISSUE TITLE
Stable Diffusion generates bad images on Nvidia T4

### ISSUE THREAD

**Issue by apivovarov** [facebookincubator/AITemplate#758]
I compiled Stable Diffusion model on diffrent hardware - on A100, on A10G and on T4.
Compiled model generates acceptable images on A100 and A10G GPUs.
But generated images on T4 (compute capability 7.5) are bad.
I tried both resolutions 512x512 and 768x768. 
Used HF models:
- stabilityai/stable-diffusion-2-1-base
- stabilityai/stable-diffusion-2-1
Example of the bad images: 
- [img1](https://pasteboard.co/mmbsNkHrgERX.png)
- [img2](https://pasteboard.co/yXx1PuB1bsW6.png)

Cuda 11.8
Driver 525.105.17

diffusers 0.16.1
transformers 4.29.2
accelerate 0.20.3
torch 2.0.0+cu118

Colab Notebook to reproduce the issue (Runtime GPU T4 free) - https://colab.research.google.com/drive/1ZzoL73rld2O4CBcJA-t7lAnEOa58Ur3s?usp=sharing
Note - Compilation takes 58 min because notebook runtime has only 2 cores

@hl475 What you think?

**Comment by hl475** [comment]
Hi @apivovarov , I don't think Meta internally has T4 so it would be hard to tell. Wondering if @terrychenism has any insights on this.

**Comment by apivovarov** [comment]
I returned back to commit [e8f17d1f9c8116b85ac945fa926f01da6d8c1536](https://github.com/facebookincubator/AITemplate/tree/e8f17d1f9c8116b85ac945fa926f01da6d8c1536) Feb 27, 2023
Images generated on T4 look good.
So, the issue was introduces sometime btw Feb 28 and Jun 7, 2023

**Comment by hl475** [comment]
[The PR ](https://github.com/facebookincubator/AITemplate/pull/765) is merged, thanks for the fix!
