### ISSUE TITLE
Question: Same Operator in Different Modules

### ISSUE THREAD

**Issue by ioeddk** [facebookincubator/AITemplate#818]
What are the differences between the same operation, `conv2d_bias` for example, that exists in the three different modules `aitemplate.nn`, `aitemplate.nn.ops`, and `aitemplate.compiler.ops`?

**Comment by hlky** [comment]
Follow from [`nn.Conv2dBias`](https://github.com/facebookincubator/AITemplate/blob/86539017294cdf80a44ead8fa95c412a52b0cb41/python/aitemplate/frontend/nn/conv2d/conv2d_bias.py#L75) -> [`nn.Conv2dBiasAct`](https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/frontend/nn/conv2d/common_conv2d_bias_act.py#L70)
`nn.Conv2dBias` is the frontend, it uses `compiler.ops.conv2d_bias`.
The difference is that frontend has attributes for the weight/bias, this functions the same as Torch, the weight/bias will be applied to the module at compile time or runtime. The raw op has no attributes, you would need to manage the weight and bias yourself.
Unless you have specific reason to use the raw op, you should probably just use the frontend.
```
nn.Conv2dBias
>>> m = nn.Conv2d(16, 33, 3, 2)
>>> input = Tensor(shape=[20, 50, 100, 16])
>>> output = m(input)
```
```
compiler.ops.conv2d_bias
X = Tensor(shape=[N, H, W, C_in], dtype="float16", name="images", is_input=True)
W = Tensor(shape=[C_out, K_h, K_w, C_in], dtype="float16", name="weight", is_input=True)
B = Tensor(shape=[C_out], dtype="float16", name="bias", is_input=True)
OP = aitemplate.compiler.ops.conv2d_bias(stride=1, pad=1, dilate=1)
Y = OP(X, W, B)
```

**Comment by aakhundov** [comment]
@hlky Thanks a lot for the detailed answer!

@ioeddk Please let us know if the answer clarifies, thanks!

**Comment by ioeddk** [comment]
The answer is satisfying. Thank you very much!
