### ISSUE TITLE
Does AIT have FlashAttention support for AMD ROCm?

### ISSUE THREAD

**Issue by duli2012** [facebookincubator/AITemplate#853]
As the title states.

**Comment by fsx950223** [comment]
You could review https://github.com/ROCmSoftwarePlatform/inference/blob/bec0bb6bc981c3571bc20a3fe51231fc44a5efe7/language/bert/bert_ait.py#L79 and install rocm AIT https://github.com/ROCmSoftwarePlatform/AITemplate/tree/merge_upstream
