### ISSUE TITLE
Slicing tensor along a fixed dimension

### ISSUE THREAD

**Issue by CanyonWind** [facebookincubator/AITemplate#869]
Please bear with me on this dumb question, can AIT support tension slicing? I basically want to do `tensor[:, ::2, :]` to slice the tensor into half size. Thanks

**Comment by kadeng** [comment]
I think what you're trying here is not directly supported, as you're trying to use a slice with a stride of 2. (::2) in the second dimension. This should be achievable using a combination of reshape, slice and reshape again, though. 

I'm thinking along the lines of doing this (pseudocode)

tensor.reshape(tensor.shape[0], tensor.shape[1]//2, 2, tensor.shape[1])[:,:,0,:]

I have not tried this, but would recommend trying that approach first.

**Comment by kadeng** [comment]
Closing this issue for now, I am sure the approach I outlined should work.
