### ISSUE TITLE
Measuring per layer acceleration

### ISSUE THREAD

**Issue by mvpatel2000** [facebookincubator/AITemplate#88]
Is there a way to measure how much speedup each cuda file / layer delivers? I'm particularly interested in StableDiffusion.

For example, my initial prior is that the matrix multiplication kernels likely don't deliver much benefit because its already so optimized, but fusing activations with norms might give a good chunk. It would be nice to somehow verify or measure this.

**Comment by antinucleon** [comment]
It is straightforward, similar to check nan function, append cuda event record code around the node in codegen: https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/backend/codegen.py#L556

Also remember to create all events in the main template: https://github.com/facebookincubator/AITemplate/blob/main/python/aitemplate/backend/main_templates.py#L366

**Comment by mvpatel2000** [comment]
Great, thanks! Will close issue for now and reopen if I hit any problems. Seems like it shouldn't be too bad
