### ISSUE TITLE
sm90/sm90a Hopper architecture Incompatibility 

### ISSUE THREAD

**Issue by ConsceIeratus** [facebookincubator/AITemplate#926]
`46 errors detected in the compilation of "mem_eff_attention_19.cu".
make: *** [Makefile:9: mem_eff_attention_19.obj] Error 255
make: *** Waiting for unfinished jobs....

2023-09-12 12:07:19,961 INFO <aitemplate.backend.builder> mem_eff_attention_19.cu:

...
98                cutlass::half_t,
99                cutlass::half_t,
100               cutlass::half_t, // ElementC
101               float // ElementAccumulator
102               >;
103   
104       // If the head_size already meets the alignment requirement, then
105       // it's safe to mark mem_align to be true to maximize the alignment
106       // benefit. Otherwise, assign false to it to use the minimal alignment.
107       constexpr const bool mem_align =
108           (64 % DefaultConfig::kAlignmentA == 0) &&
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
109           (64 % DefaultConfig::kAlignmentB == 0);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
110       using Attention = AttentionKernel<
111           cutlass::half_t, // scalar_t
112           ArchTag,
113           mem_align, // memory is aligned
114           kQueriesPerBlock,
115           kKeysPerBlock,
116           kSingleValueIteration
117       >;
118   
119       typename Attention::Params p;
...

2023-09-12 12:07:19,962 INFO <aitemplate.backend.builder> /home/ubuntu/.local/lib/python3.10/site-packages/aitemplate/3rdparty/../static/include/kernels/mem_eff_attention/kernel_forward.h:

...
270       using DefaultConfig =
271           typename cutlass::gemm::device::DefaultGemmConfiguration<
272               OpClass,
273               ArchTag,
274               scalar_t,
275               scalar_t,
276               scalar_t, // ElementC
277               accum_t // ElementAccumulator
278               >;
279       static constexpr int kAlignmentA =
280           kIsAligned ? DefaultConfig::kAlignmentA : GemmType::kMinimumAlignment;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
281       static constexpr int kAlignmentB =
282           kIsAligned ? DefaultConfig::kAlignmentB : GemmType::kMinimumAlignment;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
283       using ThreadblockShape = cutlass::gemm::
284           GemmShape<kQueriesPerBlock, kKeysPerBlock, GemmType::ThreadK>;
285       using WarpShape = cutlass::gemm::GemmShape<32, 32, GemmType::WarpK>;
286       using DefaultMma = typename cutlass::gemm::threadblock::FindDefaultMma<
287           scalar_t, // ElementA,
288           cutlass::layout::RowMajor, // LayoutA,
289           kAlignmentA,
290           scalar_t, // ElementB,
291           cutlass::layout::ColumnMajor, // LayoutB,
292           kAlignmentB,
293           accum_t,
294           cutlass::layout::RowMajor, // LayoutC,
295           OpClass,
296           ArchTag, // ArchTag
297           ThreadblockShape, // ThreadblockShape
298           WarpShape, // WarpShape
299           typename GemmType::InstructionShape, // InstructionShape
300           DefaultConfig::kStages, // Should use `DefaultConfig::kStages`, but that
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
301                                   // uses too much smem
302           typename GemmType::Operator // Operator
303           >::DefaultMma;
304       using MmaCore = typename DefaultMma::MmaCore;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
305       using IteratorA = typename DefaultMma::IteratorA;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
306       using IteratorB = typename DefaultMma::IteratorB;
307       using Mma = typename DefaultMma::ThreadblockMma;
308       using ScalingCoefsUpdater = typename DefaultAttentionScalingCoefsUpdater<
309           typename Mma::Operator::IteratorC,
310           accum_t,
311           kWarpSize>::Updater;
312       static_assert(
313           MmaCore::WarpCount::kM * MmaCore::WarpCount::kN *
314                   MmaCore::WarpCount::kK ==
315               kNumWarpsPerBlock,`

**Comment by kadeng** [comment]
Could you provide some sort of context to this issue? Most importantly: Could you try to specify it in such a way that we might be able to reproduce it? Especially, which steps led to the error message you are describing here? If there is source code of yours involved, could you quote the most relevant sections. In which environment did it occur? I assume this is on a Hopper-based system. Which CUDA Toolkit version do you use?

**Comment by ipiszy** [comment]
Hi [ArasAyen](https://github.com/ArasAyen),
The existing memory-efficient attention kernel is based on CUTLASS 2 which doesn't have SM90 specialization. To avoid compilation failure, you could try to hardcode this part (https://github.com/facebookincubator/AITemplate/blob/4ca343524e9bc6ddf317c50d0fee37459ba60251/python/aitemplate/backend/cuda/attention/mem_eff_attention.py#L83) to SM80.
A better solution is to add FlashAttention V2 to AIT as well. Please feel free to contribute to AIT if you're interested, thank you!
