### ISSUE TITLE
Would it be possible to port RotaryEmbedding to AITemplate

### ISSUE THREAD

**Issue by CanyonWind** [facebookincubator/AITemplate#939]
Hi, as `RotaryEmbedding` is critical for many usecases, wonder whether would it be possible to provide an AIT implementation example about it? Many thanks

PyTorch reference: https://github.com/lucidrains/rotary-embedding-torch/blob/main/rotary_embedding_torch/rotary_embedding_torch.py

**Comment by aakhundov** [comment]
@CanyonWind thanks for the question. At this time, we're not actively developing new example models in AIT. But we're happy to accept community contributions!

**Comment by CanyonWind** [comment]
Thanks, for sure I understand that customizing people's ask isn't a high priority. 

As an alternative solution, I noticed that for fx2ait, we can have a hybrid computation graph where part of them runs on AIT and the other on pytorch by excluding fx tracing. However, the fx tracing is error-prone when the original pytorch model is complex -- wonder whether it's possible to still build AIT modeling manually (like [the examples](https://github.com/facebookincubator/AITemplate/blob/main/examples/01_resnet-50/modeling/resnet.py)) but set part of them to be on pytorch (e.g. the RotaryEmbedding here)

**Comment by aakhundov** [comment]
> wonder whether it's possible to still build AIT modeling manually (like [the examples](https://github.com/facebookincubator/AITemplate/blob/main/examples/01_resnet-50/modeling/resnet.py)) but set part of them to be on pytorch (e.g. the RotaryEmbedding here)

I think, following [this code](https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/example/benchmark_utils.py#L65) as an example, you can try building one or more [`AITModule`s](https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/ait_module.py#L22) (a subclass of `nn.Module`) manually and then use those in a larger PT model, possibly with some native PT `nn.Module` instances in it (e.g., for the `RotaryEmbedding`).

**Comment by CanyonWind** [comment]
I understand that we can port a portion of the model to AIT and rely on pytorch for pre/post-processing or something that is independent of the AIT modeling part. 

To rephrase my question -- if the majority of the model is portable to AIT but **interleave there are modules like RotaryEmbedding that are not portable,** then do we have to split the AIT model into multiple chunks? This means we will have a very fractional graph and the more non-portable modules are in there, the more fractions the total model will be.

**Comment by aakhundov** [comment]
Yes, this is true in general: the more graph splits, the worse the performance can become. Due to smaller AIT coverage / fewer optimization opportunities + switching cost between AIT and non-AIT parts of the full model. So it's generally beneficial to strive for maximum AIT coverage, but it's not always possible.

**Comment by CanyonWind** [comment]
Was able to port RotaryEmedding with fx2ait, with some tweaks of course but it worked
