### ISSUE TITLE
AIT seems not able to achieve max along a given dim

### ISSUE THREAD

**Issue by CanyonWind** [facebookincubator/AITemplate#941]
I'm working on the fx2ait tool and blocked by porting one single line `x = x / x.amax(dim=-1, keepdim=True)` to AIT, which seems to be unreasonably annoying to achieve.

- `amax` itself isn't supported
- Changed to `max` with `x = x / x.max(dim=-1, keepdim=True)[0]`
  - `max` triggers `max_dim_reduce `, which isn't supported either
- Looked up the supported ops list [here](https://facebookincubator.github.io/AITemplate/reference/ops.html), which indicates that `argmax` and `gather` should be ready to use. And switched to 
    ```
    max_indices = torch.argmax(x, dim=-1).unsqueeze(-1)
    max_values = torch.gather(x, dim=-1, index=max_indices)
    x = x / max_values
    ```
  - It throws error saying `call_function torch.argmax` and `call_function fx2ait.acc_tracer.acc_ops.gather` aren't supported 

How come we can achieve porting complex models like BERT and Diffusion to AIT but not max? Would appreciate any guidance here

**Comment by aakhundov** [comment]
Looking at the `acc_ops.py` [here](https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/acc_tracer/acc_ops.py) in fx2ait, I have an impression that `argmax` is not supported. This is not surprising, as the ecosystem for int tensor support within AIT is not very mature (and the output of `torch.argmax` is an int tensor). cc @khabinov could you please confirm?

**Comment by aakhundov** [comment]
Taking a look.

**Comment by aakhundov** [comment]
So, from what I see in the code, currently only `sum` and `mean` reductions are supported by AIT. However, adding new ones for `amin` / `amax` shouldn't be very hard. I'll send out a PR soon, stay tuned.

**Comment by aakhundov** [comment]
@CanyonWind #942 should unblock you for now: `x = x / x.amax(dim=-1, keepdim=True)` should work. I'll need to consolidate / clean up the PR before landing.

**Comment by CanyonWind** [comment]
This is awesome, tysm for the prompt help. I will give it a try.

**Comment by CanyonWind** [comment]
@aakhundov fx2ait can now pick up `amax` for conversion but it seems throwing some error during codegen. Any suggestions on what's the issue?
```
  File "/opt/conda/envs/ait_convert_env/lib/python3.10/site-packages/fx2ait-0.2.dev1-py3.10-linux-x86_64.egg/fx2ait/fx2ait.py", line 249, in run
    self.engine = compile_model(**args)
  File "/opt/conda/envs/ait_convert_env/lib/python3.10/site-packages/aitemplate/utils/misc.py", line 93, in inner_function
    return f(*args, **kwargs)
  File "/opt/conda/envs/ait_convert_env/lib/python3.10/site-packages/aitemplate/compiler/compiler.py", line 312, in compile_model
    file_pairs = backend.codegen.gen_function_src(graph, workdir, test_name)
  File "/opt/conda/envs/ait_convert_env/lib/python3.10/site-packages/aitemplate/backend/codegen.py", line 126, in gen_function_src
    fo.write(func.gen_function())
  File "/opt/conda/envs/ait_convert_env/lib/python3.10/site-packages/aitemplate/compiler/ops/reduce/reduce_common.py", line 279, in gen_function
    return func(self._attrs)
  File "/opt/conda/envs/ait_convert_env/lib/python3.10/site-packages/aitemplate/backend/cuda/reduce/var.py", line 305, in var_gen_function
    return reduce_3d.gen_function(
  File "/opt/conda/envs/ait_convert_env/lib/python3.10/site-packages/aitemplate/backend/cuda/reduce/reduce_3d.py", line 914, in gen_function
    epilogue_scalar_code = epilogue_scalar_template.render(indent=" " * 12)
AttributeError: 'str' object has no attribute 'render'. Did you mean: 'center'?
```

**Comment by aakhundov** [comment]
Thanks for the feedback! Yeah, I see the same error in the CI. Will take a look.

**Comment by aakhundov** [comment]
@CanyonWind check out the updated version of #942. The error you've reported (as well as a few others) seem to be fixed. I still observe one error with fx2ait tests, but it may work for you purposes.

**Comment by aakhundov** [comment]
@CanyonWind #942 has landed. The new ops should be in good shape now. Let me know if you have issues.

**Comment by CanyonWind** [comment]
Thanks again and should be good to close! I don't have the bandwidth to try it out in the upcoming few days but will trust CI and your judgment. If met any issue, will either reopen or create another one.
