### ISSUE TITLE
`Fatal Python error: Floating point exception` with `run_with_tensors`

### ISSUE THREAD

**Issue by jiangwei221** [facebookincubator/AITemplate#976]
Hi,
Thanks for the great open source  inference library!
I'm working on a stable-diffusion-like model, and want to extend it with dynamic batch size and dynamic token length. I can successfully compile the model into AITemplate, but when I try to run the model with `run_with_tensors`, I met `Fatal Python error: Floating point exception`.
Do you have any suggestions how to debug this?
Thanks a lot!

**Comment by chenyang78** [comment]
Hi @jiangwei221 it's kind of hard to guess where the issue could come from. Based on the error message, you might want to check where and why the "Floating point exception" error was thrown. Thanks.

**Comment by jiangwei221** [comment]
Hi @chenyang78 , just want to update that the problem is solved. The core dump happens when I ask for certain dynamic shape, it's so strange, for example ,dynamic range from 8-64 works well without error, but if I change the dynamic range to 8-32, then I will get the core dump error.
Not sure why certain magic numbers are needed to make it work.

**Comment by chenyang78** [comment]
> Hi @chenyang78 , just want to update that the problem is solved. The core dump happens when I ask for certain dynamic shape, it's so strange, for example ,dynamic range from 8-64 works well without error, but if I change the dynamic range to 8-32, then I will get the core dump error. Not sure why certain magic numbers are needed to make it work.

Great. Thanks for the update!
