### ISSUE TITLE
Question about dynamic shape

### ISSUE THREAD

**Issue by syyxsxx** [facebookincubator/AITemplate#99]
hi, does ait support dynamic width and height?

**Comment by Suhail** [comment]
No - see this issue: https://github.com/facebookincubator/AITemplate/issues/64

**Comment by prnake** [comment]
So is there a already written min-shape stratergy to run dynamic shape models?
I'm trying to test AIT with a gpt model, and found it seems unable to handle dynamic seq_len, same as the bert example.

**Comment by antinucleon** [comment]
We will address dynamic sequences support in v0.2
