### ISSUE TITLE
windows platform cannot link _binary_constants_bin_end and _binary_constants_bin_start

### ISSUE THREAD

**Issue by joye** [facebookincubator/AITemplate#990]
In windows, I tried to use cmake to run example 07_how_to_run_pt_model, meet link error;

1>model_container_base.obj : error LNK2019: unresolved external symbol "unsigned char const * const _binary_constants_bin_start" (?_binary_constants_bin_start@@3QBEB) referenced in function "public: __cdecl ait::ModelContainerBase::ModelContainerBase(unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,class AITemplateAllocator &)" (??0ModelContainerBase@ait@@QEAA@_K0000AEAVAITemplateAllocator@@@Z)
1>model_container_base.obj : error LNK2019: unresolved external symbol "unsigned char const * const _binary_constants_bin_end" (?_binary_constants_bin_end@@3QBEB) referenced in function "public: __cdecl ait::ModelContainerBase::ModelContainerBase(unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,class AITemplateAllocator &)" (??0ModelContainerBase@ait@@QEAA@_K0000AEAVAITemplateAllocator@@@Z)

**Comment by chenyang78** [comment]
Hmm, seems this line wasn't hit in your case:

https://github.com/facebookincubator/AITemplate/blob/4b27253f7ba767de42b56fa36105b1f649ac75ed/python/aitemplate/backend/main_templates.py#L377

The existing Windows support was contributed and maintained by one of our ex-colleagues. We don't support Windows officially. Any Windows-related patches are very welcome! Thanks.

**Comment by hlky** [comment]
```
--- a/python/aitemplate/backend/codegen.py
+++ b/python/aitemplate/backend/codegen.py
@@ -49,7 +49,7 @@ from aitemplate.utils.environ import (
     multistream_mode,
 )
 from aitemplate.utils.graph_utils import split_simple_multistream_parallel_ops
-from aitemplate.utils.misc import is_debug
+from aitemplate.utils.misc import is_debug, is_windows
 
 # pylint: disable=C0103,W0613,C0301
 
@@ -1095,8 +1095,7 @@ class ModelContainerGenerator:
             set_up_constant_folding_inputs="\n".join(
                 self.set_up_constant_folding_inputs
             ),
-            # # todo: enable once this feature is fully available
-            # is_windows=is_windows(),
+            is_windows=is_windows(),
         )
         result[model_container_src_fname] = model_container_base_src
         return result
--- a/python/aitemplate/backend/main_templates.py
+++ b/python/aitemplate/backend/main_templates.py
@@ -322,13 +322,13 @@ MODEL_CONTAINER_TEMPLATE = jinja2.Template(
 #include "model_container.h"
 #include "owned_constants.h"
 
-namespace ait {
-namespace {
-
 {% if is_windows %}
 #include "windll.h"
 {% endif %}
 
+namespace ait {
+namespace {
+
 // Contains the metadata for each constant.
 constexpr std::array<ConstantInfo, {{ num_constants }}> owned_constants = {
   {{ owned_constants_init }}
```

**Comment by chenyang78** [comment]
Thanks for the investigation and sharing the patch, @hlky ! Given the comment left by the original author of windows support, "todo: enable once this feature is fully available", I am quite hesitant to apply it to the main branch, because we don't have any test coverage nor any one is actively working on Windows support. 

@joye I think you might want to try the patch shared by @hlky and see if it would work for you. Thanks!

**Comment by hlky** [comment]
The same fix was applied to my (currently unmaintained) fork [here](https://github.com/hlky/AITemplate/commit/135d52cf4a47b2eccd72347310d515723e510a0a) and [here](https://github.com/hlky/AITemplate/commit/3fe4c02b59e4e289d3d91e619f87bcc02034a041) so I can confirm it fixes this particular issue, however there are other Windows issues and just to note constants have a ~2GB limit on Windows.

**Comment by joye** [comment]
Thanks @hlky, this patch can work in my side.
